CREATE SEQUENCE quotes_seq_gen START 1000 INCREMENT 1;

CREATE TABLE quotes (
    id        serial        PRIMARY KEY,
    author    VARCHAR (512),
    content   VARCHAR (1024),
    created   TIMESTAMP     NOT NULL,
    modified  TIMESTAMP
);

INSERT INTO quotes VALUES (1, ' Pablo Picasso', 'Computers are useless.  They can only give you answers. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (2, ' Sam Ewing', 'Computers are like bikinis. They save people a lot of guesswork. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (3, ' Janet Reno', 'They have computers, and they may have other weapons of mass destruction. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (4, ' Paul Leary', 'That’s what’s cool about working with computers.  They don’t argue, they remember everything, and they don’t drink all your beer. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (5, ' Robert X. Cringely', 'If the automobile had followed the same development cycle as the computer, a Rolls-Royce would today cost $100, get a million miles per gallon, and explode once a year, killing everyone inside. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (6, ' Dave Barry', 'Computers are getting smarter all the time.  Scientists tell us that soon they will be able to talk to us.  (And by ‘they’, I mean ‘computers’.  I doubt scientists will ever be able to talk to us.) ', current_timestamp, NULL);
INSERT INTO quotes VALUES (7, ' Larry DeLuca', 'I’ve noticed lately that the paranoid fear of computers becoming intelligent and taking over the world has almost entirely disappeared from the common culture.  Near as I can tell, this coincides with the release of MS-DOS. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (8, ' Edsger W. Dijkstra', 'The question of whether computers can think is like the question of whether submarines can swim. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (9, ' Marvin Minsky', 'It’s ridiculous to live 100 years and only be able to remember 30 million bytes.  You know, less than a compact disc.  The human condition is really becoming more obsolete every minute. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (10, ' C3PO', 'The city’s central computer told you?  R2D2, you know better than to trust a strange computer! ', current_timestamp, NULL);
INSERT INTO quotes VALUES (11, ' Steve Wozniak', 'Never trust a computer you can’t throw out a window. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (12, ' Jeff Pesis', 'Hardware: The parts of a computer system that can be kicked. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (13, ' Alan Kay', 'Most software today is very much like an Egyptian pyramid with millions of bricks piled on top of each other, with no structural integrity, but just done by brute force and thousands of slaves. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (14, ' Dennie van Tassel', 'I’ve finally learned what ‘upward compatible’ means.  It means we get to keep all our old mistakes. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (15, ' Jeremy S. Anderson', 'There are two major products that come out of Berkeley: LSD and UNIX.  We don’t believe this to be a coincidence. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (16, ' End of the word according to Unix–2^32 seconds after January 1, 1970', '19 Jan 2038 at 3:14:07 AM ', current_timestamp, NULL);
INSERT INTO quotes VALUES (17, ' Microsoft senior vice president Brian Valentine describing the state of the art in OS security, 2003', 'Every operating system out there is about equal… We all suck. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (18, ' Dave Barry', 'Microsoft has a new version out, Windows XP, which according to everybody is the ‘most reliable Windows ever.‘  To me, this is like saying that asparagus is ‘the most articulate vegetable ever.‘ ', current_timestamp, NULL);
INSERT INTO quotes VALUES (19, ' Homer Simpson', 'The Internet?  Is that thing still around? ', current_timestamp, NULL);
INSERT INTO quotes VALUES (20, ' Nytwind', 'The Web is like a dominatrix.  Everywhere I turn, I see little buttons ordering me to Submit. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (21, ' Blair Houghton', 'Come to think of it, there are already a million monkeys on a million typewriters, and Usenet is nothing like Shakespeare. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (22, ' Henry Petroski', 'The most amazing achievement of the computer software industry is its continuing cancellation of the steady and staggering gains made by the computer hardware industry. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (23, ' Timm Martin', 'True innovation often comes from the small startup who is lean enough to launch a market but lacks the heft to own it. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (24, ' Alan Cooper', 'It has been said that the great scientific disciplines are examples of giants standing on the shoulders of other giants.  It has also been said that the software industry is an example of midgets standing on the toes of other midgets. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (25, ' Lou Gerstner', 'It is not about bits, bytes and protocols, but profits, losses and margins. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (26, ' Bumper sticker', 'We are Microsoft.  Resistance Is Futile.  You Will Be Assimilated. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (27, ' Mark Gibbs', 'No matter how slick the demo is in rehearsal, when you do it in front of a live audience, the probability of a flawless presentation is inversely proportional to the number of people watching, raised to the power of the amount of money involved. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (28, ' Linus Torvalds', 'The bulk of all patents are crap.  Spending time reading them is stupid.  It’s up to the patent owner to do so, and to enforce them. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (29, ' Brian Kernigan', 'Controlling complexity is the essence of computer programming. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (30, ' Ray Ozzie', 'Complexity kills.  It sucks the life out of developers, it makes products difficult to plan, build and test, it introduces security challenges, and it causes end-user and administrator frustration. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (31, ' C.A.R. Hoare', 'There are two ways of constructing a software design.  One way is to make it so simple that there are obviously no deficiencies. And the other way is to make it so complicated that there are no obvious deficiencies. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (32, ' Grady Booch', 'The function of good software is to make the complex appear to be simple. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (33, ' Walter Mossberg', 'Just remember: you’re not a ‘dummy,’ no matter what those computer books claim.  The real dummies are the people who–though technically expert–couldn’t design hardware and software that’s usable by normal consumers if their lives depended upon it. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (34, ' Bill Gates', 'Software suppliers are trying to make their software packages more ‘user-friendly’…  Their best approach so far has been to take all the old brochures and stamp the words ‘user-friendly’ on the cover. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (35, ' Bjarne Stroustrup', 'There’s an old story about the person who wished his computer were as easy to use as his telephone.  That wish has come true, since I no longer know how to use my telephone. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (36, ' Ted Nelson', 'Any fool can use a computer.  Many do. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (37, ' Edward Tufte', 'There are only two industries that refer to their customers as ‘users’. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (38, ' Rich Cook', 'Programmers are in a race with the Universe to create bigger and better idiot-proof programs, while the Universe is trying to create bigger and better idiots.  So far the Universe is winning. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (39, ' Larry Wall', 'Most of you are familiar with the virtues of a programmer.  There are three, of course: laziness, impatience, and hubris. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (40, ' Seymour Cray', 'The trouble with programmers is that you can never tell what a programmer is doing until it’s too late. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (41, ' Larry Niven', 'That’s the thing about people who think they hate computers.  What they really hate is lousy programmers. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (42, ' Bill Bryson', 'For a long time it puzzled me how something so expensive, so leading edge, could be so useless.  And then it occurred to me that a computer is a stupid machine with the ability to do incredibly smart things, while computer programmers are smart people with the ability to do incredibly stupid things.  They are, in short, a perfect match. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (43, ' Eric Raymond', 'Computer science education cannot make anybody an expert programmer any more than studying brushes and pigment can make somebody an expert painter. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (44, ' IEEE Grid newsmagazine', 'A programmer is a person who passes as an exacting expert on the basis of being able to turn out, after innumerable punching, an infinite series of incomprehensive answers calculated with micrometric precisions from vague assumptions based on debatable figures taken from inconclusive documents and carried out on instruments of problematical accuracy by persons of dubious reliability and questionable mentality for the avowed purpose of annoying and confounding a hopelessly defenseless department that was unfortunate enough to ask for the information in the first place. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (45, ' Peter Seebach', 'A hacker on a roll may be able to produce–in a period of a few months–something that a small development group (say, 7-8 people) would have a hard time getting together over a year.  IBM used to report that certain programmers might be as much as 100 times as productive as other workers, or more. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (46, ' Randall E. Stross', 'The best programmers are not marginally better than merely good ones.  They are an order-of-magnitude better, measured by whatever standard: conceptual creativity, speed, ingenuity of design, or problem-solving ability. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (47, ' Bill Gates', 'A great lathe operator commands several times the wage of an average lathe operator, but a great writer of software code is worth 10,000 times the price of an average software writer. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (48, ' Mosher’s Law of Software Engineering', 'Don’t worry if it doesn’t work right.  If everything did, you’d be out of a job. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (49, ' Bill Gates', 'Measuring programming progress by lines of code is like measuring aircraft building progress by weight. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (50, ' Gerald Weinberg', 'Writing code has a place in the human hierarchy worth somewhere above grave robbing and beneath managing. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (51, ' George Carrette', 'First learn computer science and all the theory.  Next develop a programming style.  Then forget all that and just hack. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (52, ' John Johnson', 'First, solve the problem. Then, write the code. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (53, ' Kent Beck', 'Optimism is an occupational hazard of programming; feedback is the treatment. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (54, ' L. Peter Deutsch', 'To iterate is human, to recurse divine. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (55, ' Anonymous', 'The best thing about a boolean is even if you are wrong, you are only off by a bit. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (56, ' Stan Kelly-Bootle', 'Should array indices start at 0 or 1?  My compromise of 0.5 was rejected without, I thought, proper consideration. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (57, ' Bjarne Stroustrup', 'There are only two kinds of programming languages: those people always bitch about and those nobody uses. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (58, ' Jon Ribbens', 'PHP is a minor evil perpetrated and created by incompetent amateurs, whereas Perl is a great and insidious evil perpetrated by skilled but perverted professionals. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (59, ' E.W. Dijkstra', 'The use of COBOL cripples the mind; its teaching should therefore be regarded as a criminal offense. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (60, ' E. W. Dijkstra', 'It is practically impossible to teach good programming style to students that have had prior exposure to BASIC.  As potential programmers, they are mentally mutilated beyond hope of regeneration. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (61, ' Oktal', 'I think Microsoft named .Net so it wouldn’t show up in a Unix directory listing. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (62, ' Larry Flon', 'There is no programming language–no matter how structured–that will prevent programmers from making bad programs. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (63, ' Larry Wall', 'Computer language design is just like a stroll in the park.  Jurassic Park, that is. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (64, ' Richard A. O’Keefe', 'Fifty years of programming language research, and we end up with C++? ', current_timestamp, NULL);
INSERT INTO quotes VALUES (65, ' Bob Gray', 'Writing in C or C++ is like running a chain saw with all the safety guards removed. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (66, ' Bjarne Stroustrup', 'In C++ it’s harder to shoot yourself in the foot, but when you do, you blow off your whole leg. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (67, ' Gavin Russell Baker', 'C++ : Where friends have access to your private members. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (68, ' Robert Firth', 'One of the main causes of the fall of the Roman Empire was that–lacking zero–they had no way to indicate successful termination of their C programs. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (69, ' Michael Feldman', 'Java is, in many ways, C++–. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (70, ' Alanna', 'Saying that Java is nice because it works on all OSes is like saying that anal sex is nice because it works on all genders. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (71, ' pixadel', 'Fine, Java MIGHT be a good example of what a programming language should be like.  But Java applications are good examples of what applications SHOULDN’T be like. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (72, ' Robert Sewell', 'If Java had true garbage collection, most programs would delete themselves upon execution. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (73, ' Linus Torvalds', 'Software is like sex: It’s better when it’s free. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (74, ' David Emery', 'The only people who have anything to fear from free software are those whose products are worth even less. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (75, ' Steve McConnell', 'Good code is its own best documentation. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (76, ' Eagleson’s Law', 'Any code of your own that you haven’t looked at for six or more months might as well have been written by someone else. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (77, ' Tom Cargill', 'The first 90% of the code accounts for the first 90% of the development time.  The remaining 10% of the code accounts for the other 90% of the development time. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (78, ' Francis Glassborow', 'Good programmers use their brains, but good guidelines save us having to think out every case. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (79, ' Jeff Atwood', 'In software, we rarely have meaningful requirements.  Even if we do, the only measure of success that matters is whether our solution solves the customer’s shifting idea of what their problem is. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (80, ' Bill Clinton', 'Considering the current sad state of our computer programs, software development is clearly still a black art, and cannot yet be called an engineering discipline. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (81, ' Jim McCarthy', 'You can’t have great software without a great team, and most software teams behave like dysfunctional families. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (82, ' Maurice Wilkes discovers debugging, 1949', 'As soon as we started programming, we found to our surprise that it wasn’t as easy to get programs right as we had thought.  Debugging had to be discovered.  I can remember the exact instant when I realized that a large part of my life from then on was going to be spent in finding mistakes in my own programs. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (83, ' Brian Kernighan', 'Debugging is twice as hard as writing the code in the first place.  Therefore, if you write the code as cleverly as possible, you are–by definition–not smart enough to debug it. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (84, ' Edsger W. Dijkstra', 'If debugging is the process of removing bugs, then programming must be the process of putting them in. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (85, ' Vidiu Platon', 'I don’t care if it works on your machine!  We are not shipping your machine! ', current_timestamp, NULL);
INSERT INTO quotes VALUES (86, ' Michael Sinz', 'Programming is like sex: one mistake and you’re providing support for a lifetime. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (87, ' Alan J. Perlis', 'There are two ways to write error-free programs; only the third one works. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (88, ' Bertrand Meyer', 'You can either have software quality or you can have pointer arithmetic, but you cannot have both at the same time. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (89, ' Mark Minasi', 'If McDonalds were run like a software company, one out of every hundred Big Macs would give you food poisoning, and the response would be, ‘We’re sorry, here’s a coupon for two more.’ ', current_timestamp, NULL);
INSERT INTO quotes VALUES (90, ' Martin Golding', 'Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (91, ' Paul Ehrlich', 'To err is human, but to really foul things up you need a computer. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (92, ' Mitch Radcliffe', 'A computer lets you make more mistakes faster than any invention in human history–with the possible exceptions of handguns and tequila. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (93, ' Charles H. Duell, Commissioner, U.S. Office of Patents, 1899', 'Everything that can be invented has been invented. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (94, ' Thomas J. Watson, Chairman of the Board, IBM, circa 1948', 'I think there’s a world market for about 5 computers. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (95, ' John Von Neumann, circa 1949', 'It would appear that we have reached the limits of what it is possible to achieve with computer technology, although one should be careful with such statements, as they tend to sound pretty silly in 5 years. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (96, ' Engineer at the Advanced Computing Systems Division of IBM, commenting on the microchip, 1968', 'But what is it good for? ', current_timestamp, NULL);
INSERT INTO quotes VALUES (97, ' Ken Olson, President, Digital Equipment Corporation, 1977', 'There is no reason for any individual to have a computer in his home. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (98, ' Bill Gates, 1981', '640K ought to be enough for anybody. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (99, ' Microsoft, on the development of Windows NT, 1992', 'Windows NT addresses 2 Gigabytes of RAM, which is more than any application will ever need. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (100, ' Andy Pierson', 'We will never become a truly paper-less society until the Palm Pilot folks come out with WipeMe 1.0. ', current_timestamp, NULL);
INSERT INTO quotes VALUES (101, ' Frank Lloyd Wright', 'If it keeps up, man will atrophy all his limbs but the push-button finger. ', current_timestamp, NULL);
