apiVersion: v1
kind: Service
metadata:
  labels:
    app: quotespsql
  name: quotespsql-svc
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: quotespsql
